### ISSUE TITLE
List/Info Plugin

### ISSUE THREAD

**Issue by victoryforphil** [DisnodeTeam/Disnode#35]
Plugin to list all loaded Plugins and their settings (like prefix). Also show other useful info. **_Could possibly add this feature to the Disnode Plugin._** 

Info:
 - Plugins
 - Shard ID
 - Servers/Users
 - Instances
 - MSG/s
 - Commands

**Comment by Azorant** [comment]
i got the sharding

**Comment by FireGamer3** [comment]
Not done
